#created on: 11.03.2012
package org.bgp4j.netty.drools

#list any import classes here.
import org.bgp4.config.nodes.PeerConfiguration;

import org.bgp4j.netty.BGPv4Constants.java;
import org.bgp4j.netty.drools.NetworkChannel;
import org.bgp4j.netty.protocol.open.OpenPacket;

rule "Your First Rule"

    when
        $nc : NetworkChannel()
        $config : PeerConfiguration() 
    then
		nc.sendPacket();
end

rule "Your Second Rule"
    #include attributes such as "salience" here...
    when
        #conditions
    then
        #actions

end
